### ISSUE TITLE
Installation simplification

### ISSUE THREAD

**Issue by Timple** [dheera/rosboard#37]
You might not be aware, but `<package format="3">` enables conditional dependencies in the package.xml. [Like so](https://github.com/RoboSense-LiDAR/rslidar_sdk/blob/8cbf42008026b4c9cbdc69fa189e2fcbf73c2334/package.xml)

This could ease the installation procedure I think.

Once pointcloud support is there I will certainly give this dashboard a go. (And will create a PR for this if not already done so).

**Comment by dheera** [comment]
Oh awesome! I wasn't aware of this. Is this supported all the way back to melodic, kinetic, and preferably also indigo?

**Comment by Timple** [comment]
Certainly as of kinetic. Indigo I'm not sure.

**Comment by dheera** [comment]
Hi, the latest version should now support dual ROS1/ROS2 without running a configuration script, thanks to a pull request by another user. Thanks for the suggestion!
