### ISSUE TITLE
saving already done configuration so that we cannot add everything again and again

### ISSUE THREAD

**Issue by dineshrboson** [dheera/rosboard#76]
can you add this feature?

**Comment by dheera** [comment]
Hi,
The latest release should remember your configuration between refreshes. Are you running the latest version? If not can you hit F12, type `window.localStorage`  in the console and paste the output?

**Comment by dheera** [comment]
Closing this issue for now, since the most recent version does auto-save layouts so it persists between refreshes.

Please re-open if you discover bugs and that behavior is not working correctly.
