### ISSUE TITLE
[Feature request] Publishing data

### ISSUE THREAD

**Issue by Henrycious** [dheera/rosboard#98]
Hello!

Some people already requested this, but is there an easy (and dirty?) way of publishing any data from rosboard to the local ROS program? 
I stared writing my master-thesis and want to use your Webinterface to primarily view the topics data but also want to be able to publish simple messages (bool, int) ( e.g. by a button or checkbox) to other local nodes.
I'd also like to do some programming but im fairly new to ROS and Webdevelopment in general, so I don't really know on where to start. Maybe you can help me out or tell me where to implement such thing as publishing data.

I really appreciate any help you can provide.

**Comment by Henrycious** [comment]
I just copied a part of the robotwebtools/roslibjs (http://wiki.ros.org/roslibjs/Tutorials/BasicRosFunctionality) into the index.html and added a button to publish data (w/o cards or anything, just a plain button on the start-page), its not pretty, but it works for now

**Comment by Hao-Starrr** [comment]
Hi Henrycious,
I am facing the same problem, may i know how do you solve it?

I found 
```
var ros = new ROSLIB.Ros({
    url : 'ws://localhost:9090'
  });
```
is conflict with WebSocketV1Transport. But if skip this, 

```
var addTwoIntsClient = new ROSLIB.Service({
    ros : ros,
    name : '/add_two_ints',
    serviceType : 'rospy_tutorials/AddTwoInts'
  });
```
there ros is not defined when creating a service or topic.

Have you handled this problem?

**Comment by Hao-Starrr** [comment]
@Henrycious  Thank you Henrycious! I will try this.
